### PR TITLE
fix: layout on Posts page

### PR DESCRIPTION
**Pull request by kemiljk**

### CODE REVIEW

**Review by tonyspiro — CHANGES_REQUESTED** [review]
Looks great. Couple things:
1. Remove the category tags from the posts list view (they look bunched up on mobile)
2. Add the category tags to the single post view

**Comment by tonyspiro** [comment]
Also, the view code on GitHub link should point to this repo.

**Comment by kemiljk** [comment]
Shall we make the repo public?

**Comment by tonyspiro** [comment]
Yes, done.

**Pull request merged**
